#!/bin/bash

image_name="nvim-alpine"
main_container_name="nvim-main"
script="${BASH_SOURCE[0]}"
script_dir="$(cd "$(dirname "${script}")" && pwd)"


if [ -z "$1" ]; then
    echo "Usage: nvim <path> <file>"
    exit 1
fi

passed_path=""

if [ -n "$2" ]; then
    if [ "${2:0:1}" = "/" ]; then
        passed_path="$2"
    elif [ "$2" = "." ] || [ "$2" = "./" ]; then
        passed_path="$1"
    else
        passed_path="$1/$2"
    fi
else
    passed_path="$1"
fi


if [ -n "$script_dir/clipboard.txt" ]; then
    rm -rf "$script_dir/clipboard.txt"
fi

touch "$script_dir/clipboard.txt"

if [ -z "$(docker images -q $image_name)" ]; then
    echo "Image does not exist. Building now..."
    docker-buildx build -t $image_name $script_dir
fi

if [ ! "$(docker ps -aq -f name=$main_container_name)" ]; then
    echo "Container does not exist. Creating now..."
    docker run -itd \
        --name $main_container_name \
        -v $script_dir/.config/nvim:/root/.config/nvim \
        -v nvim_state:/root/.local/state/nvim \
        -v nvim_share:/root/.local/share/nvim \
        -v $script_dir/clipboard.txt:/root/clipboard-sync/clipboard.txt \
        $image_name
fi

(file_path="$script_dir/clipboard.txt"
while true; do
  content=$(cat "$file_path" | sed -e '$ d')
  if [ "$content" != "" ]; then
    if [ -n pbcopy ]; then
      pbcopy < "$file_path"
    elif [ -n xclip ]; then
      xclip -selection clipboard < "$file_path"
    elif [ -n xsel ]; then
      xsel --clipboard < "$file_path"
    else
      break
    fi
    echo "" > "$file_path"
  fi

  sleep 1
done) &

clipboard_pid=$!

inner_path=""

if [ -z $2 ]; then
    inner_path=""
else
    inner_path=" $2"
fi

# if inner_path is a file, go up one level

if [ -f "$passed_path" ]; then
    passed_path=$(dirname "$passed_path")
fi

docker run --rm -it \
    --volumes-from $main_container_name \
    -v $passed_path:/mnt/volume \
    --workdir /mnt/volume \
    $image_name nvim$inner_path 

kill $clipboard_pid

